#!/usr/bin/bash

if [ $# -eq 0 ]; then
    exit 1
fi

if [ "$1" == "-h" ]; then
    echo Usage:
    echo "  buildnrun TAKSNAME"
    echo Options:
    echo "  -i INPUTFILE"
    echo "  -o OUTPUTFILE"
    exit 0
fi

hasTaskName=false

for arg in $*; do
    if [ -e "$arg.cpp" ]; then
        build $arg
        hasTaskName=true
        break
    fi
done

if !($hasTaskName); then
    echo buildnrun: Missing TAKSNAME
    exit 1
fi

run $*
